sudo: required

language: node_js

node_js:
  - "10"
  - "8"
  - "6"

services:
  - docker

before_install:
  - docker pull arangodb
  - docker run -d -p 8529:8529 -e ARANGO_ROOT_PASSWORD=root arangodb

script:
  - npm run test
